import { useEffect, type ReactNode } from "react";
import { Link } from "wouter";

const UPDATED = "October 9, 2026";

function PageMeta({ title, description, path }: { title: string; description: string; path: string }) {
  useEffect(() => {
    document.title = title + " | CINTEXA";
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null;
    if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); }
    meta.content = description;
    let canonical = document.querySelector('link[rel="canonical"]') as HTMLLinkElement | null;
    if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); }
    canonical.href = `https://cintexa.com${path}`;
    let robots = document.querySelector('meta[name="robots"]') as HTMLMetaElement | null;
    if (!robots) { robots = document.createElement("meta"); robots.name = "robots"; document.head.appendChild(robots); }
    robots.content = "index, follow";
  }, [title, description, path]);
  return null;
}

function Shell({ eyebrow, title, intro, children, path, description }: { eyebrow: string; title: string; intro: string; children: ReactNode; path: string; description: string }) {
  return <div className="cx-section"><PageMeta title={title} description={description} path={path} /><div className="cx-container max-w-4xl">
    <p className="cx-eyebrow">{eyebrow}</p><h1 className="cx-display mt-3 text-3xl sm:text-5xl">{title}</h1>
    <p className="mt-5 max-w-3xl text-lg leading-8 text-[hsl(var(--fg-muted))]">{intro}</p>
    <p className="mt-3 text-sm text-[hsl(var(--fg-muted))]">Last updated: {UPDATED}</p>
    <div className="mt-10 space-y-8">{children}</div>
    <p className="mt-10 border-t border-[hsl(var(--border))] pt-6 text-sm text-[hsl(var(--fg-muted))]">Questions? Contact <a className="underline text-[hsl(var(--accent))]" href="mailto:info@cintexa.com">info@cintexa.com</a> or visit our <Link className="underline text-[hsl(var(--accent))]" href="/contact">contact page</Link>.</p>
  </div></div>;
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section><h2 className="cx-display text-2xl">{title}</h2><div className="mt-3 space-y-3 leading-7 text-[hsl(var(--fg-muted))]">{children}</div></section>;
}

const googleAds = <a className="underline" href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google advertising technologies</a>;
const googleSettings = <a className="underline" href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">Google Ads Settings</a>;
const googlePrivacy = <a className="underline" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a>;

export function PrivacyPolicy() {
  return <Shell eyebrow="Legal · Privacy" title="Privacy Policy" path="/privacy-policy"
    description="Read how CINTEXA handles personal information, Firebase and Google services, accounts, job applications, cookies, analytics, advertising, retention and privacy rights."
    intro="This policy explains how CINTEXA collects, uses, stores and shares information when you visit cintexa.com, contact us, create or use an account, apply for a role, or use our digital services. The exact data processed depends on which features and providers are enabled.">
    <Section title="1. Who is responsible for your information?"><p>CINTEXA (“CINTEXA”, “we”, “us” or “our”) operates this website and related digital services. For privacy questions, requests or complaints, contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a>. We aim to handle personal information in line with applicable law, including Ghana’s Data Protection Act, 2012 (Act 843), and other privacy laws that may apply based on your location.</p></Section>
    <Section title="2. Information we collect"><ul className="list-disc space-y-2 pl-6">
      <li><strong>Contact and enquiry details:</strong> name, email, phone number, organisation, project requirements, message content and information you choose to provide.</li>
      <li><strong>Account information:</strong> identifiers, authentication-related records, profile details, account settings and information associated with features you use. Password authentication is handled by the configured identity provider; do not send passwords to us by email.</li>
      <li><strong>Job and opportunity applications:</strong> contact details, CV/resume, work history, education, portfolio links, qualifications and other information you submit in an application.</li>
      <li><strong>Service and transaction records:</strong> project correspondence, service selections, support requests, invoices or payment status where relevant. Payment card data should be handled by the applicable payment provider rather than submitted in free-text forms.</li>
      <li><strong>Technical and usage data:</strong> IP address or approximate location, device and browser type, pages viewed, referring pages, diagnostic events, timestamps, security logs and cookie or consent preferences, depending on the services enabled.</li>
      <li><strong>Communications and notifications:</strong> message preferences, delivery status and whether you subscribe to optional updates or allow browser notifications.</li>
    </ul><p>Please do not submit sensitive personal information unless it is genuinely necessary and we have provided an appropriate way to share it.</p></Section>
    <Section title="3. How we use information and our purposes"><p>We use information to answer enquiries; provide, secure and support requested services; create and administer accounts; assess job applications; communicate about projects; process agreed transactions; remember privacy choices; prevent fraud, abuse and technical failures; understand website performance; comply with legal duties; and improve content and services. Marketing messages are sent only where permitted and with any consent required by law. Submitting a contact form does not automatically subscribe you to unrelated promotional email.</p></Section>
    <Section title="4. Legal bases and choices"><p>Where a law such as the GDPR applies, processing may rely on steps requested before entering a contract, performance of a contract, legal obligations, legitimate interests balanced against your rights, or consent. Where consent is the basis, you can withdraw it at any time; withdrawal does not make earlier lawful processing unlawful. We will not use optional analytics or advertising cookies before consent where applicable law requires prior consent.</p></Section>
    <Section title="5. Firebase and Google services"><p>Depending on features configured for the live site, CINTEXA may use Firebase and related Google services for authentication, app infrastructure, analytics, data storage or messaging. Those services may process identifiers, technical information and service events to perform their functions. Firebase products are not all necessarily enabled in every environment. Google’s information is available in the {googlePrivacy} and its documentation for the specific service. We aim to configure each service for its intended purpose and applicable consent requirements.</p><p>We may also rely on website hosting and security providers, email delivery services, application and database providers, spam-prevention tools, payment providers, recruitment tools and analytics or advertising partners where needed. The relevant provider may process information on our behalf or as an independent controller under its own terms.</p></Section>
    <Section title="6. Cookies, analytics and advertising"><p>Cookies and similar technologies (such as local storage, SDK identifiers and pixels) can remember settings, keep services secure, measure use and support advertising. Essential technologies support requested functions. Optional analytics can help us understand page usage and site performance. If advertising is enabled, Google and its partners may use advertising cookies or similar identifiers to serve, measure and limit ads, detect invalid traffic, and—where permitted by settings and consent—personalise ads based on visits to this or other websites.</p><p>You can review personalised-ad choices using {googleSettings} and learn how Google uses data in {googleAds}. Your browser may also provide controls to clear or block cookies. Those controls may affect sign-in and other essential features. Industry opt-out choices may be available through the Network Advertising Initiative or Digital Advertising Alliance, depending on your region and participating providers.</p><p>Our cookie preference control lets you accept all, save selected categories, or choose necessary technologies only. You can reopen preferences using the “Cookie preferences” control shown on the site. A browser setting or policy page does not replace consent where the law requires a consent mechanism.</p></Section>
    <Section title="7. Contact forms and customer communications"><p>Information submitted through forms is used to respond to your request, assess a project or provide the service you asked for. Form submissions may be processed by hosting, spam protection and email delivery providers to validate and route the message. We limit access to people who need the information to respond or perform their work. Please avoid including confidential or highly sensitive information in a general enquiry form.</p></Section>
    <Section title="8. Job applications and recruitment"><p>Application data is used to review eligibility and suitability, contact candidates, schedule interviews and manage recruitment. It may be shared with authorised people involved in selection and with relevant technical providers. If an application is unsuccessful, we retain it only as long as reasonably necessary for the recruitment process, legitimate follow-up, recordkeeping or legal requirements, subject to applicable law. You may ask us about deletion or correction of your application information.</p></Section>
    <Section title="9. Notifications and marketing"><p>Browser push notifications require permission through your browser or device and can usually be disabled in its settings. Service-related messages may be necessary to provide a feature you requested. Optional newsletters or marketing messages should include a practical way to unsubscribe. We do not treat permission for browser notifications as blanket consent for email marketing.</p></Section>
    <Section title="10. Sharing, international transfers and security"><p>We do not sell personal information for money. We may disclose it to service providers, professional advisers, payment or delivery partners, or public authorities where reasonably necessary and lawful. We may also share information in connection with a business reorganisation, subject to appropriate safeguards. Providers may process information in countries outside Ghana or your country of residence. Where required, we use legally recognised transfer safeguards. We apply reasonable technical and organisational security measures, but no website, transmission or storage system can be guaranteed completely secure.</p></Section>
    <Section title="11. Retention"><p>We keep personal information only for as long as reasonably necessary for the purpose for which it was collected, including delivering services, maintaining required business records, handling disputes, enforcing agreements and meeting legal or security obligations. Enquiry records, account records, recruitment submissions, security logs and consent records may have different retention periods. We periodically review retention and delete or de-identify data when it is no longer needed, unless law or a legitimate claim requires longer retention.</p></Section>
    <Section title="12. Your rights"><p>Depending on the law that applies, you may have the right to request access to personal information, correction of inaccurate information, deletion, restriction or objection to certain processing, a copy in a portable format, or withdrawal of consent. You may also complain to the relevant data protection authority. Contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a> to make a request; we may ask for information to verify your identity and will respond within the time required by applicable law. Certain exceptions may apply.</p><p>In Ghana, information about the Data Protection Commission is available at <a className="underline" href="https://dataprotection.org.gh/" target="_blank" rel="noopener noreferrer">dataprotection.org.gh</a>.</p></Section>
    <Section title="13. Children and third-party websites"><p>CINTEXA’s website is intended for a general business audience and is not designed to knowingly collect personal information from children. If you believe a child has provided personal information, contact us so we can assess and take appropriate action. Links to external websites are provided for convenience; their privacy practices are controlled by those sites, and you should review their policies separately.</p></Section>
    <Section title="14. Updates"><p>We may update this policy as our services, providers or legal requirements change. The “Last updated” date above indicates the latest revision. Material changes may be highlighted on the site where appropriate.</p></Section>
  </Shell>;
}

export function Terms() {
  return <Shell eyebrow="Legal" title="Terms & Conditions" path="/terms"
    description="CINTEXA terms of use for website visitors, accounts, services, submissions, intellectual property, payments, prohibited activity, disclaimers and termination."
    intro="These terms govern access to cintexa.com and the general use of CINTEXA’s website and digital features. A signed proposal, order or service agreement may add specific terms for a project; where legally valid and expressly agreed, that document governs the project-specific matters it addresses.">
    <Section title="1. Acceptance and eligibility"><p>By accessing or using the website, you agree to these terms. If you use it on behalf of an organisation, you confirm you are authorised to accept terms for that organisation. If you do not agree, do not use the relevant service.</p></Section>
    <Section title="2. Website use and acceptable conduct"><p>You may use the site for lawful purposes and in accordance with these terms. You must not attempt unauthorised access; disrupt systems or other users; bypass security; introduce malware; send spam or fraudulent submissions; scrape or harvest information in ways that violate law or rights; impersonate another person; infringe intellectual property; or use the site to facilitate unlawful or harmful activity.</p></Section>
    <Section title="3. Accounts and security"><p>You are responsible for providing accurate account information, safeguarding your credentials and activity performed through your account. Notify us promptly if you suspect unauthorised access. Do not share credentials in public or use another person’s account without permission. We may require verification, suspend access or restrict a feature where reasonably necessary for security, compliance or protection of users.</p></Section>
    <Section title="4. Services, proposals and deliverables"><p>Website content describes services in general and is not itself a binding promise that a particular service, feature or delivery date is available. Project scope, specifications, responsibilities, milestones, acceptance criteria, support, maintenance, intellectual property, dependencies and delivery dates should be documented in a written proposal or agreement. Estimates depend on the accuracy and completeness of information provided and may change when scope or requirements change.</p></Section>
    <Section title="5. Payments, taxes and third-party costs"><p>Where paid services are agreed, the applicable written proposal, invoice or order states the fees, currency, taxes, payment milestones, due dates, refund terms and any late-payment consequences. Do not assume a payment, subscription or refund term unless it has been agreed or is required by law. Third-party software, hosting, domain, payment processing, messaging and subscription charges may be separate. A change in third-party pricing or availability may affect the cost or delivery of a project.</p></Section>
    <Section title="6. User submissions and feedback"><p>You are responsible for ensuring that material you submit—such as text, images, documents, code, CVs or feedback—is accurate to the best of your knowledge and that you have the right to provide it. Do not submit unlawful, infringing, deceptive, confidential or malicious material through a general form. You retain rights you already hold in your submissions. You allow CINTEXA to use them only as reasonably necessary to respond to your request, evaluate an application, provide an agreed service, maintain security or as otherwise explained to you or authorised by law.</p></Section>
    <Section title="7. Intellectual property"><p>The CINTEXA name, branding, website design, original text, graphics and other site materials are owned by CINTEXA or licensed to it and are protected by applicable laws. You may view and use public content for personal or internal business reference, but must not reproduce, republish, sell or create derivative works from protected material without permission, except where the law allows. Ownership and licence rights for commissioned software, designs, documentation and other client deliverables must be stated in the relevant project agreement. Third-party and open-source components remain subject to their own licences.</p></Section>
    <Section title="8. Third-party tools and links"><p>Our site or services may link to or integrate with external platforms, payment providers, cloud infrastructure, analytics, communication tools or other services. Those providers have their own terms, policies, availability and security practices. CINTEXA does not control external websites and is not responsible for their content or policies. Review provider terms before using or connecting a third-party service.</p></Section>
    <Section title="9. Availability, changes and maintenance"><p>We aim to keep the website useful and secure, but do not guarantee that it will always be uninterrupted, error-free or available on every device. We may modify, suspend or discontinue website features for maintenance, security, legal or operational reasons. Where appropriate, we will make reasonable efforts to communicate material changes to active customers.</p></Section>
    <Section title="10. Disclaimers"><p>Unless expressly agreed in writing and to the extent permitted by law, the website and its general content are provided on an “as available” basis without a guarantee that the content is complete, current or suitable for a particular purpose. Business, technology and tutorial content is informational and does not guarantee any commercial outcome. Project services are governed by their written scope and applicable law.</p></Section>
    <Section title="11. Limitation of liability"><p>To the maximum extent permitted by applicable law, CINTEXA is not liable for indirect, incidental, special or consequential loss, loss of profits, revenue, data, goodwill or business opportunity arising from general website use. Nothing in these terms excludes or limits liability that cannot lawfully be excluded or limited, including any mandatory consumer rights. Any project-specific limitation of liability must be set out in the relevant written agreement and remains subject to applicable law.</p></Section>
    <Section title="12. Suspension and termination"><p>We may suspend or terminate access where we reasonably believe there is a material breach, unlawful activity, a security threat, abuse of services or a legal requirement. Where appropriate, we may provide notice and an opportunity to resolve the issue. Ending access does not remove obligations or rights that accrued before termination, or provisions that by their nature should continue to apply.</p></Section>
    <Section title="13. Privacy, updates and governing law"><p>Our processing of personal information is described in the <Link className="underline" href="/privacy-policy">Privacy Policy</Link> and <Link className="underline" href="/cookie-policy">Cookie Policy</Link>. We may update these terms by publishing a revised version. Unless a project agreement or mandatory law states otherwise, these general terms are intended to be interpreted consistently with the laws applicable to CINTEXA’s operations, including the laws of Ghana, without overriding mandatory rights available to you in your location.</p></Section>
    <Section title="14. Contact"><p>Questions about these terms can be sent to <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a>.</p></Section>
  </Shell>;
}

export function CookiePolicy() {
  return <Shell eyebrow="Legal · Cookies" title="Cookie Policy" path="/cookie-policy"
    description="CINTEXA cookie policy explains essential, analytics and advertising cookies, Firebase and Google technologies, consent and user choices."
    intro="This policy explains cookies and similar technologies that may be used on CINTEXA’s website. The exact technologies depend on the features and providers enabled in the live deployment. Optional analytics and advertising should be activated only in accordance with your preferences and applicable law.">
    <Section title="1. What cookies and similar technologies are"><p>Cookies are small files stored by a browser. Similar technologies include local storage, software development kit (SDK) identifiers, pixels, tags and device identifiers. They can remember a choice, support a secure session, measure activity or help deliver advertising.</p></Section>
    <Section title="2. Essential and functional technologies"><p>Essential technologies support core features such as security, login/session management, form protection, network routing and saving your cookie preference. They are used to provide a service you request or to maintain security. Blocking them may prevent parts of the site from working. Preference technologies may remember settings such as your consent selection.</p></Section>
    <Section title="3. Analytics cookies"><p>If analytics is enabled and you consent where required, CINTEXA may use Firebase Analytics or Google Analytics to understand page views, navigation, general usage patterns and technical performance. These services may use cookies, app identifiers or other signals. Analytics data helps us diagnose problems and improve the website. We aim to avoid collecting more information than needed for these purposes.</p></Section>
    <Section title="4. Advertising cookies and Google technology"><p>If Google AdSense or another advertising provider is enabled, cookies or similar identifiers may be used to show ads, limit repeated impressions, detect invalid traffic, measure ad performance and personalise ads where permitted. Google and its partners may use information about visits to this and other sites to provide relevant advertising. Personalised advertising depends on provider settings, region and applicable consent requirements.</p><p>Manage personalised ads using <a className="underline" href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">Google Ads Settings</a>. Read about <a className="underline" href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google advertising technologies</a> and the <a className="underline" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a>. Your choices in Google’s settings do not necessarily replace the consent controls required on this website.</p></Section>
    <Section title="5. Firebase-related technologies"><p>Firebase Authentication may use browser storage or tokens to maintain authentication. Firebase Analytics may use identifiers or similar technologies to report usage. Firebase Cloud Messaging, if enabled, may process a registration token to deliver notifications after permission is granted. Other Firebase products may use technologies required for their own functionality. Which products and identifiers apply depends on the site’s configuration; not every Firebase product is necessarily enabled.</p></Section>
    <Section title="6. Your choices and consent"><p>Use the CINTEXA cookie preference control to accept all categories, save a selected combination or choose necessary technologies only. You can reopen it using the “Cookie preferences” control on the website. Analytics and marketing are off by default until you make a choice. Where prior consent is required by law, optional technologies should not be set or activated before valid consent.</p><p>You can also clear or block cookies through your browser. If you block essential storage, login, preference storage or other site functions may be affected. To change Google’s personalised-ad settings, use the Google controls linked above. Consent choices stored in this browser may not automatically apply to other browsers or devices.</p></Section>
    <Section title="7. Retention and policy updates"><p>Cookie and identifier lifetimes vary by technology and provider. Some last only for a session; others may persist until expiry or deletion. We review technologies and update this policy when the site’s implementation changes. For privacy questions, contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a>.</p></Section>
  </Shell>;
}

export function Disclaimer() {
  return <Shell eyebrow="Legal · Content" title="Disclaimer" path="/disclaimer"
    description="CINTEXA disclaimer covering business analysis, financial information, technology recommendations, tutorials, comparisons, third-party links and affiliate disclosures."
    intro="CINTEXA publishes educational and informational content about business technology, software, digital operations and growth. Content is intended to help readers ask better questions and explore options; it is not a substitute for professional advice tailored to your circumstances.">
    <Section title="1. General information, not professional advice"><p>Articles, tutorials, templates, business analyses, planning frameworks and examples are provided for general information. They are not legal, accounting, tax, investment, financial, cybersecurity or other regulated professional advice, and do not establish a professional-client relationship. Consult a suitably qualified professional who understands your circumstances before making decisions that require specialist judgement.</p></Section>
    <Section title="2. Business and financial analysis"><p>Business assessments, forecasts, examples, budgets, market observations and performance suggestions may rely on assumptions, information supplied by a user or data available at the time of writing. They are not guarantees of profitability, investment performance, revenue, savings, funding, customer growth or business survival. Verify key facts and adapt recommendations to your own market, financial position, risk tolerance and legal obligations.</p></Section>
    <Section title="3. Technology recommendations and tutorials"><p>Software, product, hosting, cloud, AI, security and platform recommendations reflect the context described and may change as vendors update features, prices, licences, security practices or availability. Tutorials may not cover every configuration or risk. Test changes in a safe environment, back up important information, review current official documentation and obtain qualified support where appropriate. You are responsible for assessing suitability before adopting a product or executing instructions.</p></Section>
    <Section title="4. Comparisons, examples and case studies"><p>Product comparisons are based on stated criteria and may not include every available option. Any scenario labelled illustrative, sample, hypothetical or estimated is not a claim of completed client work or verified results. CINTEXA does not promise that a result achieved in one situation will be replicated in another. Actual outcomes depend on factors outside our control.</p></Section>
    <Section title="5. External links and third-party services"><p>Links to external websites and products are provided for convenience and research. They do not automatically constitute an endorsement, and CINTEXA does not control the accuracy, availability, security or privacy practices of third-party resources. Use third-party services at your own discretion and review their current terms, policies and documentation.</p></Section>
    <Section title="6. Affiliate links, sponsorships and advertising"><p>If content contains an affiliate link, sponsorship or paid placement, CINTEXA should identify that relationship clearly and close to the relevant content. If you purchase through an affiliate link, CINTEXA may receive a commission at no additional cost to you, where such a programme is active and disclosed. Advertising does not guarantee endorsement of an advertiser’s claims; evaluate offers independently.</p></Section>
    <Section title="7. Accuracy and limitation"><p>We make reasonable efforts to publish useful and accurate material, but information may be incomplete, outdated or contain errors. Content is provided without a guarantee of completeness or suitability to the extent permitted by law. Nothing in this disclaimer limits any right or liability that cannot lawfully be limited.</p></Section>
    <Section title="8. Contact"><p>To report an error or ask a question about published content, email <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a>.</p></Section>
  </Shell>;
}
