import { useEffect } from "react";
import { Link } from "wouter";

function PageMeta({ title, description, path }: { title: string; description: string; path: string }) {
  useEffect(() => {
    document.title = title;
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null;
    if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); }
    meta.content = description;
    let canonical = document.querySelector('link[rel="canonical"]') as HTMLLinkElement | null;
    if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); }
    canonical.href = `https://cintexa.com${path}`;
    let robots = document.querySelector('meta[name="robots"]') as HTMLMetaElement | null;
    if (!robots) { robots = document.createElement("meta"); robots.name = "robots"; document.head.appendChild(robots); }
    robots.content = "index, follow";
  }, [title, description, path]);
  return null;
}
function Shell({ eyebrow, title, intro, children, path, description }: { eyebrow: string; title: string; intro: string; children: React.ReactNode; path: string; description: string }) {
  return <div className="cx-section"><PageMeta title={title + " | CINTEXA"} description={description} path={path} /><div className="cx-container max-w-4xl"><p className="cx-eyebrow">{eyebrow}</p><h1 className="cx-display mt-3 text-3xl sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[hsl(var(--fg-muted))]">{intro}</p><div className="mt-10 space-y-8">{children}</div></div></div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section><h2 className="cx-display text-2xl">{title}</h2><div className="mt-3 space-y-3 leading-7 text-[hsl(var(--fg-muted))]">{children}</div></section>;
}

export function About() {
  return <Shell eyebrow="About CINTEXA" title="Technology and digital systems built around real business needs" path="/about" description="Learn about CINTEXA, our mission, vision, working approach and digital business solutions for organisations in Ghana and beyond." intro="CINTEXA is a technology and digital business solutions company focused on helping organisations improve how they operate, reach customers and deliver services. We bring software, websites, automation and business technology together around practical goals.">
    <Section title="Our background"><p>CINTEXA was created around a simple idea: technology should solve a clearly understood problem and remain useful after launch. Our work spans digital presence, software development, connected business systems, e-commerce and digital growth support.</p><p>We approach each engagement by first understanding the organisation, its customers, existing tools and operational constraints. The recommended solution should fit the problem rather than add complexity for its own sake.</p></Section>
    <Section title="Mission"><p>To design and deliver accessible, dependable digital solutions that help businesses organise work, serve customers and make informed decisions.</p></Section>
    <Section title="Vision"><p>To help more organisations use practical technology to build resilient operations, reach wider markets and create sustainable opportunities, particularly across Ghana and Africa.</p></Section>
    <Section title="What CINTEXA helps solve"><ul className="list-disc space-y-2 pl-6"><li>Outdated websites and disconnected digital customer experiences.</li><li>Manual processes that create repeated data entry and missed follow-ups.</li><li>Scattered customer, sales and marketing information.</li><li>Online selling workflows that need better product, order and customer management.</li><li>Limited visibility into digital performance and business operations.</li></ul></Section>
    <Section title="Who we serve"><p>We work with small and medium-sized businesses, founders, service providers, retailers, professional teams and organisations that need a practical digital foundation or want to improve existing systems. Scope and delivery are agreed around the client’s goals, budget, available information and support needs.</p></Section>
    <Section title="How we work"><p>Our process typically includes discovery, requirements and success measures, solution design, implementation, testing, launch and ongoing improvement. We explain assumptions, identify dependencies and avoid promising results that cannot be supported by evidence. Security, accessibility, maintainability and ownership are considered throughout.</p></Section>
    <Section title="Company and contact information"><p>CINTEXA operates digitally and serves clients through online communication and project collaboration. For project enquiries, email <a className="underline text-[hsl(var(--accent))]" href="mailto:info@cintexa.com">info@cintexa.com</a> or visit our <Link className="underline text-[hsl(var(--accent))]" href="/contact">contact page</Link>. Follow us on <a className="underline" href="https://web.facebook.com/profile.php?id=61591131675150" target="_blank" rel="noopener noreferrer">Facebook</a> and <a className="underline" href="https://www.tiktok.com/@cintexadotcom" target="_blank" rel="noopener noreferrer">TikTok</a>.</p><p>We will publish verified team biographies and project information when approved for public release. We do not invent staff credentials, client endorsements or project outcomes.</p></Section>
    <Link href="/get-started" className="cx-btn cx-btn-primary">Discuss a project</Link>
  </Shell>;
}

const CASES = [
  { title: "Business website and enquiry workflow", status: "Illustrative project scenario", problem: "A service business receives enquiries through multiple channels and has no consistent record of follow-up.", assessment: "Map enquiry sources, response ownership, required information and the points where prospective customers are lost.", solution: "A responsive service website, structured contact form, clear service pages and a documented lead follow-up workflow.", implementation: "Define the content and form fields, validate submissions, route enquiries to a responsible contact, and test mobile accessibility and confirmation messages.", results: "No client result is claimed. A real engagement would report measured response time, qualified enquiries and conversion against a recorded baseline.", technology: "Responsive web development, form validation, analytics configured with consent, and CRM integration where selected." },
  { title: "Small-business e-commerce foundation", status: "Illustrative project scenario", problem: "A retailer wants to sell online but product information, stock updates, payments and delivery steps are not documented in one process.", assessment: "Review catalogue quality, inventory ownership, payment settlement, delivery coverage, returns and customer support.", solution: "A mobile-friendly product catalogue and checkout connected to a defined order fulfilment process.", implementation: "Prepare product data, configure a suitable payment provider, test successful and failed payments, and document fulfilment and refund handling.", results: "No sales uplift or conversion figure is asserted. Performance should be measured after launch using order completion, fulfilment time, cancellation and support data.", technology: "E-commerce storefront, payment-provider integration, order records and analytics." },
  { title: "Administrative workflow automation", status: "Illustrative project scenario", problem: "Staff repeatedly copy information between forms, spreadsheets and email, making hand-offs difficult to track.", assessment: "Document the current process, data owners, approval steps, exceptions and baseline time per task.", solution: "A validated intake form, centralised records, task notifications and a reviewable status workflow.", implementation: "Pilot one workflow, test permissions and exception handling, train users and keep a manual fallback during rollout.", results: "No time-saving percentage is claimed. Compare task duration, error rate and overdue work before and after deployment.", technology: "Web forms, workflow automation, database records and role-based access." }
];
export function CaseStudies() {
  return <Shell eyebrow="Case studies" title="Business problems, solution design and measurable outcomes" path="/case-studies" description="Review CINTEXA case-study formats showing problem assessment, solution, implementation, measurement and technology without fabricated results." intro="Good case studies explain the work and the evidence behind its outcome. The examples below are clearly labelled illustrative scenarios, not claims about completed client engagements. Verified client case studies can replace them when permission and supporting data are available.">
    {CASES.map((item) => <article key={item.title} className="cx-card"><p className="cx-eyebrow">{item.status}</p><h2 className="cx-display mt-2 text-2xl">{item.title}</h2><div className="mt-5 space-y-4">{[["Problem",item.problem],["Assessment",item.assessment],["Solution",item.solution],["Implementation",item.implementation],["Results",item.results],["Technology used",item.technology]].map(([label,text]) => <section key={label}><h3 className="font-semibold">{label}</h3><p className="mt-1 leading-7 text-[hsl(var(--fg-muted))]">{text}</p></section>)}</div></article>)}
    <p className="text-sm text-[hsl(var(--fg-muted))]">Have a project requirement? <Link href="/get-started" className="underline text-[hsl(var(--accent))]">Share it with CINTEXA</Link>.</p>
  </Shell>;
}

export function PrivacyPolicy() {
  return <Shell eyebrow="Legal · Privacy" title="Privacy Policy" path="/privacy-policy" description="CINTEXA privacy policy explaining personal information, account data, cookies, Firebase, analytics, advertising, retention and user choices." intro="This policy explains how CINTEXA may collect, use, store and share information when you visit our website, contact us, create an account or apply for an opportunity. Review the live implementation and update this policy whenever services or providers change.">
    <Section title="Information we may collect"><p>Information you provide may include your name, email address, phone number, organisation, project requirements, account details, contact messages and job-application information. Technical information may include device and browser details, approximate usage events, security logs and cookie or consent preferences.</p></Section>
    <Section title="How information is used"><p>We use information to respond to enquiries, provide requested services, manage accounts, process applications, protect the website, improve performance, send service messages and—where you have the appropriate choice or permission—send marketing updates. We do not treat a service enquiry as blanket consent to unrelated marketing.</p></Section>
    <Section title="Firebase and other providers"><p>Depending on the features enabled, CINTEXA may use Firebase or related Google services for authentication, database storage, file storage, analytics, notifications or application security. Data is processed according to the provider’s terms and configuration. Other providers may support hosting, email delivery, payment processing, spam prevention and analytics. Only enable providers actually used by the live site and link their current privacy documentation.</p></Section>
    <Section title="Cookies, analytics and advertising"><p>The website may use essential technologies to operate sessions, remember preferences and protect services. If analytics or advertising technologies are enabled, they may use cookies or similar identifiers to measure visits, limit fraud, report performance or personalise ads according to provider settings and applicable consent rules. Google advertising cookies may allow Google and its partners to serve ads based on visits to this or other sites. Users can review Google’s advertising settings at <a className="underline" href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">Google Ads Settings</a> and learn about Google’s data practices at <a className="underline" href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google advertising technologies</a>.</p><p>Cookie controls should reflect the technologies actually installed. Where applicable law requires prior consent, non-essential analytics or advertising technologies must not run before valid consent. A policy page alone is not a consent mechanism.</p></Section>
    <Section title="Job applications and notifications"><p>Application information is used to assess suitability, contact applicants and administer recruitment. Access should be limited to authorised people. Career alerts and marketing communications should have a clear purpose and appropriate unsubscribe option. Push notifications require browser permission and can be disabled in device or browser settings.</p></Section>
    <Section title="Retention, security and sharing"><p>We retain personal information only for as long as reasonably necessary for the stated purpose, legal obligations, dispute handling and security. Retention periods depend on the record type and applicable law. We use access controls and reasonable safeguards, but no internet transmission or storage method can be guaranteed completely secure. We do not sell personal data. Information may be shared with service providers, professional advisers or authorities where necessary and lawful.</p></Section>
    <Section title="Your choices and rights"><p>Depending on your location, you may have rights to access, correct, delete, restrict or object to certain processing, or withdraw consent. Contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a> to make a request. We may need to verify your identity and may retain information where the law permits or requires it. Applicable laws may include Ghana’s Data Protection Act, 2012 (Act 843) and other privacy laws based on your location.</p><p>Privacy questions may also be directed to Ghana’s <a className="underline" href="https://dataprotection.org.gh/" target="_blank" rel="noopener noreferrer">Data Protection Commission</a>.</p></Section>
    <Section title="Children, updates and contact"><p>The site is intended for a general business audience and is not designed to collect children’s data knowingly. We may update this policy as the service changes. The effective date should be reviewed and updated before publication; contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a> with privacy questions.</p></Section>
  </Shell>;
}
export function Terms() {
  return <Shell eyebrow="Legal" title="Terms and Conditions" path="/terms" description="CINTEXA terms covering website use, accounts, services, user submissions, intellectual property, payments, prohibited activities and disclaimers." intro="These terms describe the general rules for using CINTEXA’s website and digital services. A signed proposal or service agreement may add project-specific terms and will govern where legally agreed. Obtain legal review before relying on these terms for a particular transaction.">
    <Section title="Website use"><p>Use the site lawfully and do not interfere with its security, availability or other users. Do not attempt unauthorised access, upload malicious code, abuse forms, scrape protected information or misrepresent your identity.</p></Section>
    <Section title="Accounts and submissions"><p>You are responsible for keeping account credentials secure and providing accurate information. Notify us if you suspect unauthorised account use. Do not submit information you have no right to share. We may suspend access where necessary to protect users, systems or legal rights.</p></Section>
    <Section title="Services, scope and payments"><p>Service scope, deliverables, timelines, fees, payment schedules, acceptance criteria, support and ownership should be set out in a proposal, order or written agreement. No price or delivery commitment applies unless agreed in writing. Where payments are due, invoices and agreed payment terms apply. Third-party fees and subscriptions may be separate.</p></Section>
    <Section title="Intellectual property"><p>CINTEXA retains rights in its pre-existing tools, methods, brand and materials. Client-specific ownership or licences for commissioned work should be stated in the applicable agreement, including treatment of third-party software, open-source components, fonts, stock media and provider services. Do not reproduce CINTEXA content or marks without permission except as allowed by law.</p></Section>
    <Section title="Third-party services and availability"><p>External websites, APIs and service providers are governed by their own terms. We may update or suspend features for maintenance, security or operational reasons. We will make reasonable efforts to communicate material service changes where appropriate, but uninterrupted availability is not guaranteed.</p></Section>
    <Section title="Disclaimers and liability"><p>Website content is provided for general information and may not fit your specific circumstances. To the extent permitted by law, CINTEXA disclaims implied warranties and is not liable for indirect or consequential losses arising from use of the site. Nothing in these terms excludes liability that cannot lawfully be excluded. Any project-specific liability limits must be stated in the relevant agreement.</p></Section>
    <Section title="Termination, changes and contact"><p>We may restrict access for a serious breach or security risk. Updated terms take effect when published unless stated otherwise. Questions about these terms can be sent to <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a>.</p></Section>
  </Shell>;
}
export function CookiePolicy() {
  return <Shell eyebrow="Legal · Cookies" title="Cookie Policy" path="/cookie-policy" description="CINTEXA cookie policy covering essential cookies, analytics, advertising, Firebase-related technologies, consent and user controls." intro="Cookies and similar technologies can help a website function, understand usage and support advertising. The technologies used by CINTEXA depend on the services enabled in the live deployment.">
    <Section title="Essential technologies"><p>These technologies support core functions such as security, session handling, form protection and remembering privacy choices. If disabled, some features may not work as expected.</p></Section>
    <Section title="Analytics technologies"><p>If analytics is enabled, cookies or similar identifiers may measure page visits, traffic sources, events and technical performance. Configure analytics to respect applicable consent requirements and avoid collecting unnecessary personal information.</p></Section>
    <Section title="Advertising technologies"><p>If Google AdSense or other advertising is enabled, providers may use cookies or similar identifiers to deliver ads, limit repeated impressions, detect invalid traffic, measure performance or personalise advertising where permitted. Google’s advertising information is available at <a className="underline" href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google advertising technologies</a>.</p></Section>
    <Section title="Firebase and related services"><p>Firebase Authentication, Analytics, Cloud Messaging and other Google services may use browser storage, tokens or identifiers to deliver their specific functions. The exact technologies depend on which Firebase products are enabled and how they are configured.</p></Section>
    <Section title="Your choices"><p>Use the website’s cookie preference controls where provided, adjust browser settings, and review Google Ads Settings for personalised-ad choices. Blocking essential storage may affect login or other site functions. Where prior consent is legally required, non-essential cookies should remain disabled until consent is granted. Contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a> with questions.</p></Section>
  </Shell>;
}
export function Disclaimer() {
  return <Shell eyebrow="Legal" title="Disclaimer" path="/disclaimer" description="CINTEXA disclaimer for business advice, technology recommendations, tutorials, comparisons, third-party links and informational content." intro="CINTEXA publishes information to help readers understand business technology and digital operations. The material is general information and should not be treated as a substitute for advice tailored to your circumstances.">
    <Section title="Business and financial information"><p>Business analysis, examples, planning suggestions and financial or operational discussions are educational. They do not constitute legal, accounting, tax, investment or other regulated professional advice. Consult a qualified professional for decisions that require specialist judgement.</p></Section>
    <Section title="Technology recommendations"><p>Software, hosting, cybersecurity and product recommendations reflect the stated context and may change as products, pricing, availability and security conditions change. Test products against your own requirements and review current vendor documentation before adoption.</p></Section>
    <Section title="Case studies and examples"><p>Any example explicitly labelled illustrative or hypothetical is a scenario, not a claim of completed client work. CINTEXA does not claim client results, performance improvements or endorsements unless they are supported by evidence and approved for publication.</p></Section>
    <Section title="External links and affiliate relationships"><p>Links to third-party websites are provided for convenience and do not imply endorsement. External content and privacy practices are controlled by their respective owners. If affiliate links or sponsored content are used, the relationship should be disclosed clearly alongside the relevant recommendation.</p></Section>
    <Section title="Accuracy and contact"><p>We aim to keep published material useful and accurate, but errors or outdated details may remain. Contact <a className="underline" href="mailto:info@cintexa.com">info@cintexa.com</a> to report an issue.</p></Section>
  </Shell>;
}
